/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         external_user_id: "external_user_id",
 *         webhook_urls: ["webhook_urls"]
 *     }
 */
export interface UpdateTriggerWebhooksOpts {
    /**
     * The external user ID who owns the trigger
     */
    external_user_id: string;
    /** Array of webhook URLs to set */
    webhook_urls: string[];
}
