/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         external_user_id: "external_user_id",
 *         workflow_ids: ["workflow_ids"]
 *     }
 */
export interface UpdateTriggerWorkflowsOpts {
    /**
     * The external user ID who owns the trigger
     */
    external_user_id: string;
    /** Array of workflow IDs to set */
    workflow_ids: string[];
}
