/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             id: "id",
 *             external_user_id: "external_user_id"
 *         }
 *     }
 */
export interface ActionsReloadPropsRequest {
    "x-async-handle"?: string;
    body: Pipedream.ReloadPropsOpts;
}
