/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id",
 *         external_user_id: "external_user_id"
 *     }
 */
export interface RunActionOpts {
    "x-async-handle"?: string;
    /** The action component ID */
    id: string;
    /** The external user ID */
    external_user_id: string;
    /** The configured properties for the action */
    configured_props?: Record<string, unknown>;
    /** The ID for dynamic props */
    dynamic_props_id?: string;
}
