/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface TriggersListRequest {
    /**
     * The cursor to start from for pagination
     */
    after?: string;
    /**
     * The cursor to end before for pagination
     */
    before?: string;
    /**
     * The maximum number of results to return
     */
    limit?: number;
    /**
     * A search query to filter the triggers
     */
    q?: string;
    /**
     * The ID or name slug of the app to filter the triggers
     */
    app?: string;
}
