/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AccountsListRequest {
    /**
     * The app slug or ID to filter accounts by.
     */
    app_id?: string;
    external_user_id?: string;
    /**
     * The OAuth app ID to filter by, if applicable
     */
    oauth_app_id?: string;
    /**
     * The cursor to start from for pagination
     */
    after?: string;
    /**
     * The cursor to end before for pagination
     */
    before?: string;
    /**
     * The maximum number of results to return
     */
    limit?: number;
    /**
     * Whether to retrieve the account's credentials or not
     */
    include_credentials?: boolean;
}
