/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AccountsRetrieveRequest {
    /**
     * Whether to retrieve the account's credentials or not
     */
    include_credentials?: boolean;
}
