/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         app_slug: "app_slug",
 *         cfmap_json: "cfmap_json",
 *         connect_token: "connect_token"
 *     }
 */
export interface CreateAccountRequest {
    /**
     * The app slug or ID to filter accounts by.
     */
    app_id?: string;
    external_user_id?: string;
    /**
     * The OAuth app ID to filter by, if applicable
     */
    oauth_app_id?: string;
    /** The app slug for the account */
    app_slug: string;
    /** JSON string containing the custom fields mapping */
    cfmap_json: string;
    /** The connect token for authentication */
    connect_token: string;
    /** Optional name for the account */
    name?: string;
}
