/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AppsListRequest {
    /**
     * The cursor to start from for pagination
     */
    after?: string;
    /**
     * The cursor to end before for pagination
     */
    before?: string;
    /**
     * The maximum number of results to return
     */
    limit?: number;
    /**
     * A search query to filter the apps
     */
    q?: string;
    /**
     * The key to sort the apps by
     */
    sort_key?: Pipedream.AppsListRequestSortKey;
    /**
     * The direction to sort the apps
     */
    sort_direction?: Pipedream.AppsListRequestSortDirection;
    /**
     * Only return apps in these categories
     */
    category_ids?: string | string[];
}
