/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * End user account data, returned from the API.
 */
export interface Account {
    /** The unique ID of the account. */
    id?: string;
    /** The custom name of the account if set. */
    name?: string;
    /** The external ID associated with the account. */
    external_id?: string;
    /** Indicates if the account is healthy. Pipedream will periodically retry token refresh and test requests for unhealthy accounts */
    healthy?: boolean;
    /** Indicates if the account is no longer active */
    dead?: boolean;
    app?: Pipedream.App;
    /** The date and time the account was created, an ISO 8601 formatted string */
    created_at?: string;
    /** The date and time the account was last updated, an ISO 8601 formatted string */
    updated_at?: string;
    /** The credentials associated with the account, if the `include_credentials` parameter was set to true in the request */
    credentials?: Record<string, unknown>;
    /** The date and time the account's credentials expiration, an ISO 8601 formatted string */
    expires_at?: string;
    /** The error message if the account is unhealthy or dead, null otherwise */
    error?: string;
    /** The date and time the account was last refreshed, an ISO 8601 formatted string */
    last_refreshed_at?: string;
    /** The date and time the account will next be refreshed, an ISO 8601 formatted string */
    next_refresh_at?: string;
}
