/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response object for a Pipedream app category
 */
export interface AppCategory {
    /** ID of the app category */
    id?: string;
    /** The human-readable name of the app category */
    name?: string;
    /** A short description of the app category */
    description?: string;
}
