/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Options for creating a server-side client
 */
export interface ClientOpts {
    /** The client ID for authentication */
    client_id?: string;
    /** The client secret for authentication */
    client_secret?: string;
    /** The API URL to use (defaults to https://api.pipedream.com/) */
    api_url?: string;
}
