/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

export interface Component {
    /** The key that uniquely identifies the component. */
    key: string;
    /** The human-readable name of the component, e.g. 'GitLab: List Commits' */
    name: string;
    /** The latest version of the component, in SemVer format. */
    version: string;
    configurable_props: Pipedream.ConfigurableProp[];
    /** A description of the component */
    description?: string;
    /** The type of component (trigger or action) */
    component_type?: string;
    /** Indicates if a File Stash ID is optional or required to run the component */
    stash?: Component.Stash;
}

export namespace Component {
    /**
     * Indicates if a File Stash ID is optional or required to run the component
     */
    export type Stash = "optional" | "required";
    export const Stash = {
        Optional: "optional",
        Required: "required",
    } as const;
}
