/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received after configuring a component's prop
 */
export interface ConfigurePropResponse {
    /** Available options for the configured prop */
    options?: Pipedream.PropOption[];
    /** Any errors that occurred during configuration */
    errors?: string[];
}
