/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response object for creating an OAuth token
 */
export interface CreateOAuthTokenResponse {
    access_token: string;
    token_type: string;
    expires_in: number;
}
