/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response received after creating a connect token
 */
export interface CreateTokenResponse {
    /** The Connect Link URL */
    connect_link_url: string;
    /** The expiration time of the token in ISO 8601 format */
    expires_at: string;
    /** The generated token */
    token: string;
}
