/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Options for creating a browser-side client
 */
export interface CreateBrowserClientOpts {
    /** The API URL to use */
    api_url?: string;
}
