/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request options for deleting a deployed trigger
 */
export interface DeleteTriggerOpts {
    /** Whether to ignore errors during deactivation hook */
    ignore_hook_errors?: boolean;
}
