/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received after deploying a trigger
 */
export interface DeployTriggerResponse {
    data: Pipedream.DeployedComponent;
}
