/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An event emitted by a trigger
 */
export interface EmittedEvent {
    /** The event's payload */
    e: Record<string, unknown>;
    /** The event's type (set to 'emit' currently) */
    k: string;
    /** The event's timestamp in epoch milliseconds */
    ts: number;
    /** The event's unique ID */
    id: string;
}
