/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response returned by the API in case of an error
 */
export interface ErrorResponse {
    /** The error message */
    error: string;
    /** The error code */
    code?: string;
    /** Additional error details */
    details?: Record<string, unknown>;
}
