/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when retrieving a single app
 */
export interface GetAppResponse {
    data: Pipedream.App;
}
