/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when retrieving a list of components
 */
export interface GetComponentsResponse {
    data: Pipedream.Component[];
    page_info: Pipedream.PageInfo;
}
