/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response received when retrieving trigger workflows
 */
export interface GetTriggerWorkflowsResponse {
    workflow_ids: string[];
}
