/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response received when retrieving trigger webhooks
 */
export interface GetTriggerWebhooksResponse {
    webhook_urls: string[];
}
