/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when listing deployed triggers
 */
export interface GetTriggersResponse {
    data: Pipedream.DeployedComponent[];
    page_info: Pipedream.PageInfo;
}
