/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Different ways in which customers can authorize requests to HTTP endpoints
 */
export enum HTTPAuthType {
  None = "none",
  StaticBearer = "static_bearer_token",
  OAuth = "oauth",
}
