/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when listing accounts
 */
export interface ListAccountsResponse {
    data: Pipedream.Account[];
    page_info: Pipedream.PageInfo;
}
