/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when listing apps
 */
export interface ListAppsResponse {
    data: Pipedream.App[];
    page_info: Pipedream.PageInfo;
}
