/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PageInfo {
    count?: number;
    total_count?: number;
    start_cursor?: string;
    end_cursor?: string;
}
