/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The environment in which the server client is running
 */
export type ProjectEnvironment = "development" | "production";
export const ProjectEnvironment = {
    Development: "development",
    Production: "production",
} as const;
