/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response received when retrieving project info
 */
export interface ProjectInfoResponse {
    apps: ProjectInfoResponse.Apps.Item[];
}

export namespace ProjectInfoResponse {
    export type Apps = Apps.Item[];

    export namespace Apps {
        export interface Item {
            /** ID of the app. Only applies for OAuth apps. */
            id?: string;
            /** The name slug of the target app */
            name_slug: string;
        }
    }
}
