/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A configuration option for a component's prop
 */
export interface PropOption {
    /** The human-readable label for the option */
    label: string;
    value?: unknown;
}
