/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request options for reloading a component's props when dealing with dynamic props
 */
export interface ReloadPropsOpts {
    /** The component ID */
    id: string;
    /** The external user ID */
    external_user_id: string;
    /** Whether this operation should block until completion */
    blocking?: boolean;
    /** The configured properties for the component */
    configured_props?: Record<string, unknown>;
    /** The ID for dynamic props */
    dynamic_props_id?: string;
    /** Handle for async operations */
    async_handle?: string;
}
