/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response from reloading component props
 */
export interface ReloadPropsResponse {
    /** The updated configurable properties */
    configurable_props?: Pipedream.ConfigurableProp[];
}
