/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The response received after running an action. See https://pipedream.com/docs/components/api#returning-data-from-steps for more details.
 */
export interface RunActionResponse {
    exports?: unknown;
    os?: unknown;
    ret?: unknown;
    /** The ID of the File Stash that was used to sync the action's /tmp directory */
    stash_id?: string;
}
