/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Options for starting the connection process
 */
export interface StartConnectOpts {
    /** ID of the iframe element to use */
    iframe?: string;
}
