/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Parameters for token validation
 */
export interface ValidateTokenParams {
    /** The app ID to validate against */
    app_id: string;
    /** The OAuth app ID */
    oauth_app_id?: string;
}
