/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response received when validating a connect token
 */
export interface ValidateTokenResponse {
    app?: Pipedream.App;
    /** Error message if validation failed */
    error?: string;
    /** URI to redirect to on error */
    error_redirect_uri?: string;
    /** OAuth app ID if applicable */
    oauth_app_id?: string;
    /** Name of the project app */
    project_app_name?: string;
    /** Environment of the project */
    project_environment?: string;
    /** ID of the project */
    project_id?: string;
    /** Support email for the project */
    project_support_email?: string;
    /** Whether the token validation was successful */
    success: boolean;
    /** URI to redirect to on success */
    success_redirect_uri?: string;
}
