/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AppsListRequestSortDirection = "asc" | "desc";
export const AppsListRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
