/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AppsListRequestSortKey = "name" | "name_slug" | "featured_weight";
export const AppsListRequestSortKey = {
    Name: "name",
    NameSlug: "name_slug",
    FeaturedWeight: "featured_weight",
} as const;
