/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PipedreamEnvironment = {
    Canary: "https://api2.pipedream.com",
    Dev: "https://api.${DEV_NAMESPACE}.gkes.pipedream.net",
    Prod: "https://api.pipedream.com",
} as const;

export type PipedreamEnvironment =
    | typeof PipedreamEnvironment.Canary
    | typeof PipedreamEnvironment.Dev
    | typeof PipedreamEnvironment.Prod;
