/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         external_user_id: "external_user_id",
 *         project_id: "project_id"
 *     }
 */
export interface CreateTokenRequest {
    /** List of allowed origins for CORS */
    allowed_origins?: string[];
    /** URI to redirect to on error */
    error_redirect_uri?: string;
    /** Your end user ID, for whom you're creating the token */
    external_user_id: string;
    /** The ID of the project */
    project_id: string;
    /** URI to redirect to on success */
    success_redirect_uri?: string;
    /** Webhook URI for notifications */
    webhook_uri?: string;
}
