/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface TokensValidateRequest {
    params?: Pipedream.ValidateTokenParams;
}
