/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         external_user_id: "external_user_id",
 *         account_id: "account_id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ProxyPutRequest {
    /**
     * The external user ID for the proxy request
     */
    external_user_id: string;
    /**
     * The account ID to use for authentication
     */
    account_id: string;
    /**
     * Request body to forward to the target API
     */
    body: Record<string, unknown>;
}
